import { FiGithub, FiTwitter } from "react-icons/fi";
import { BrandMark } from "@/components/ui/BrandMark";
import { APP_NAME } from "@/constants/options";

export function Footer() {
  const year = new Date().getFullYear();

  return (
    <footer className="border-t border-border">
      <div className="mx-auto flex max-w-6xl flex-col items-center gap-4 px-5 py-10 text-center sm:flex-row sm:justify-between sm:px-8 sm:text-left">
        <div className="flex items-center gap-2.5">
          <BrandMark size={22} />
          <span className="font-display text-sm font-semibold text-text">
            {APP_NAME}
          </span>
        </div>

        <p className="text-xs text-text-faint">
          &copy; {year} {APP_NAME}. Recommendations generated by AI — always double-check before movie night.
        </p>

        <div className="flex items-center gap-3">
          <a
            href="https://github.com"
            target="_blank"
            rel="noreferrer noopener"
            aria-label="GitHub"
            className="flex h-8 w-8 items-center justify-center rounded-full border border-border text-text-muted transition-colors hover:border-border-strong hover:text-text focus-visible:outline-2 focus-visible:outline-cyan-soft"
          >
            <FiGithub size={14} />
          </a>
          <a
            href="https://twitter.com"
            target="_blank"
            rel="noreferrer noopener"
            aria-label="Twitter"
            className="flex h-8 w-8 items-center justify-center rounded-full border border-border text-text-muted transition-colors hover:border-border-strong hover:text-text focus-visible:outline-2 focus-visible:outline-cyan-soft"
          >
            <FiTwitter size={14} />
          </a>
        </div>
      </div>
    </footer>
  );
}
